# Generated by Django 4.1.4 on 2022-12-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='decription',
            new_name='description',
        ),
    ]
